package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "js_files",
    srcs = glob([
        "lib/*.js",
        "package.json",
        "webpack.config.js",
    ]),
)